apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        type: LoadBalancer
    ports:
      web:
        expose:
          default: true
        exposedPort: 80
      websecure:
        expose:
          default: false
